
HTTP_VERB_DELETE = 'delete'
HTTP_VERB_PUT    = 'put'
HTTP_VERB_GET    = 'get'
HTTP_VERB_PATCH  = 'patch'
HTTP_VERB_POST   = 'post'

HTTP_VERBS = {
    HTTP_VERB_POST,
    HTTP_VERB_PUT,
    HTTP_VERB_GET,
    HTTP_VERB_DELETE,
    HTTP_VERB_PATCH
}